/** api/generate-images.js */
export const maxDuration = 300;
import { fal } from "@fal-ai/client";
fal.config({ credentials: process.env.FAL_KEY });

const CONCEPTS={hook:"High-impact editorial advertising photography with immediate thumbnail clarity and one unmistakable subject.",insight:"Credible documentary photography, analytical and professional, natural navy, ivory and warm orange accents.",magazine:"Premium contemporary magazine photography, refined cinematic realism, natural texture and subtle visual tension."};
const PHOTO_TEMPLATES=["photo-hook","editorial-photo","photo-data-hybrid"];
function count(v){const n=Number(v);return Number.isFinite(n)?Math.max(0,Math.min(2,Math.floor(n))):0}
function clean(v,max=10000){return String(v||"").replace(/\u0000/g,"").trim().slice(0,max)}
function sleep(ms){return new Promise(r=>setTimeout(r,ms))}
function imageResult(provider,url,index){return{id:`${provider}-${Date.now()}-${index}`,provider,imageUrl:url}}
function canGenerateImage({photoRequirement,templateType,designMode}){if(photoRequirement==="none")return false;if(!PHOTO_TEMPLATES.includes(templateType)&&photoRequirement!=="required")return false;if(designMode==="info-heavy"&&!PHOTO_TEMPLATES.includes(templateType))return false;return true}
function compositionInstruction(c={},designMode="photo-heavy"){
  const area=c.reservedTextArea||"lower-left",subject=c.subjectPosition||"right-center",shot=c.cameraShot||"medium-wide",density=c.backgroundDensity||"low";
  const densityRule=density==="low"?"Use a clean, simple background with very few competing objects.":"Use a realistic moderately detailed environment, but keep the reserved text area visually quiet.";
  const modeRule=designMode==="hybrid"?"Compose the subject on roughly one half of the frame and leave a clean structured zone for one or two data points added later.":"Let the real-world scene and action dominate while preserving a generous negative-space text zone.";
  return `Camera: ${shot}. Place the primary subject at ${subject}. Keep the ${area} region calm and low-detail for Korean text added later. ${densityRule} ${modeRule} Keep faces, hands, products and key actions outside the text zone.`;
}
function roleInstruction(role="insight"){
  const map={hook:"Create one instantly understandable moment with visual tension or a surprising real-life situation.",evidence:"Show an observable real-world behavior or measurement context, not an abstract claim.",comparison:"Show a single coherent scene that makes the contrast understandable without a split-screen or collage.",case:"Show a specific believable situation with concrete place, action and limited people.",solution:"Show the changed behavior or improved operating situation in action, not a generic success pose.",action:"Show the exact practical action the audience should take.",cta:"Use a restrained, premium closing scene with ample negative space."};
  return map[role]||"Show a specific real-world action that directly explains the slide message.";
}
function profileInstruction(profile={}){const persona=clean(profile.speakerPersona,200),audience=clean(profile.targetAudience,250);if(!persona&&!audience)return"";return `Audience context: ${audience||"the intended audience"}. Tone cue: ${persona||"credible and natural"}. Reflect this through setting, casting and behavior only when it helps the message; do not automatically depict the speaker's profession.`}
function buildPrompt(prompt,concept,imageComposition,role,designMode,contentProfile){
  const scene=clean(prompt),style=CONCEPTS[concept]||CONCEPTS.hook;
  return `${scene}\n\n${style}\n${roleInstruction(role)}\n${compositionInstruction(imageComposition,designMode)}\n${profileInstruction(contentProfile)}\n\nHard requirements:\n- vertical 4:5 Instagram image\n- photorealistic editorial or documentary photograph\n- a specific place, concrete action, clear number of people, camera angle and advertising/content context\n- one coherent scene; no collage, split screen, infographic, chart, poster or UI overlay\n- no generic office, boardroom, laptop-viewing person, handshake, empty business pose or meaningless stock-photo scene unless explicitly essential\n- realistic faces, hands, anatomy, products, architecture and lighting\n- Every storefront sign, signboard, menu board, banner, poster, window notice, price board, paper notice, digital display and illuminated panel must be completely blank and plain colored, turned away from the camera, cropped out, heavily defocused, or covered by natural glare.\n- Do not generate letters, characters, glyphs, symbols, numbers, pseudo-writing, Chinese-like, Korean-like, Japanese-like or English-like text, logos, logo-like marks, watermarks or brand marks.\n- Express commercial-street atmosphere through lighting, awnings, entrances, display windows, architecture, pedestrian behavior and spatial depth instead of written signage.\n- preserve the requested location, action, camera angle, subject position and negative space`.trim();
}
async function generateFal(prompt,n){if(!n)return[];if(!process.env.FAL_KEY)throw new Error("FAL_KEY가 없습니다.");const model=process.env.FAL_MODEL?.trim()||"fal-ai/flux/dev";const input={prompt,image_size:{width:1080,height:1350},num_images:n,num_inference_steps:32,guidance_scale:3.8,enable_safety_checker:true,output_format:"png"};const negativeModels=(process.env.FAL_NEGATIVE_PROMPT_MODELS||"").split(",").map(x=>x.trim()).filter(Boolean);if(negativeModels.includes(model))input.negative_prompt="text, letters, characters, glyphs, symbols, numbers, pseudo-writing, Chinese-like text, Korean-like text, Japanese-like text, English-like text, logos, brand marks, watermarks, readable signs, malformed hands, malformed faces";const result=await fal.subscribe(model,{input,logs:true});const raw=result?.data?.images;if(!Array.isArray(raw))throw new Error("FAL 응답에 images 배열이 없습니다.");return raw.map((x,i)=>imageResult("fal",typeof x==="string"?x:x?.url,i)).filter(x=>/^https?:\/\//.test(x.imageUrl||""))}
function parseReplicateModel(value){const model=clean(value||"black-forest-labs/flux-schnell",300);if(/^[a-f0-9]{64}$/i.test(model))return{type:"version",version:model};const[path,version]=model.split(":");if(version&&/^[a-f0-9]{64}$/i.test(version))return{type:"version",version};const[owner,name]=path.split("/");return{type:"official",owner:owner||"black-forest-labs",name:name||"flux-schnell"}}
async function createPrediction(info,prompt){const endpoint=info.type==="version"?"https://api.replicate.com/v1/predictions":`https://api.replicate.com/v1/models/${encodeURIComponent(info.owner)}/${encodeURIComponent(info.name)}/predictions`;const body=info.type==="version"?{version:info.version,input:{prompt,aspect_ratio:"4:5",output_format:"png"}}:{input:{prompt,aspect_ratio:"4:5",output_format:"png"}};const r=await fetch(endpoint,{method:"POST",headers:{Authorization:`Bearer ${process.env.REPLICATE_API_TOKEN}`,"Content-Type":"application/json",Prefer:"wait=60"},body:JSON.stringify(body)});const raw=await r.text();let d;try{d=JSON.parse(raw)}catch{throw new Error("Replicate 응답을 읽지 못했습니다.")};if(!r.ok)throw new Error(d?.detail||d?.error||`Replicate 오류 HTTP ${r.status}`);return d}
async function waitPrediction(p){let cur=p;for(let i=0;i<20;i++){if(cur?.status==="succeeded")return cur;if(["failed","canceled"].includes(cur?.status))throw new Error(cur?.error||`Replicate ${cur.status}`);if(!cur?.urls?.get)break;await sleep(5000);const r=await fetch(cur.urls.get,{headers:{Authorization:`Bearer ${process.env.REPLICATE_API_TOKEN}`}});cur=await r.json()}throw new Error("Replicate 생성 대기 시간이 초과됐습니다.")}
function urls(output){if(typeof output==="string")return[output];if(Array.isArray(output))return output.filter(x=>typeof x==="string");if(output&&typeof output==="object")return[output.url,output.image,output.imageUrl,output.output].filter(x=>typeof x==="string");return[]}
async function generateReplicate(prompt,n){if(!n)return[];if(!process.env.REPLICATE_API_TOKEN)throw new Error("REPLICATE_API_TOKEN이 없습니다.");const info=parseReplicateModel(process.env.REPLICATE_MODEL),out=[];for(let i=0;i<n;i++){let p=await createPrediction(info,prompt);if(["starting","processing"].includes(p?.status))p=await waitPrediction(p);urls(p?.output).filter(u=>/^https?:\/\//.test(u)).forEach((u,j)=>out.push(imageResult("replicate",u,`${i}-${j}`)))}return out}
function extractGeminiImages(data){const out=[];for(const candidate of data?.candidates||[])for(const part of candidate?.content?.parts||[]){const inline=part?.inlineData||part?.inline_data;if(inline?.data){const mime=inline.mimeType||inline.mime_type||"image/png";out.push(`data:${mime};base64,${inline.data}`)}}return out}
async function generateGemini(prompt,n){if(!n)return[];if(!process.env.GEMINI_API_KEY)throw new Error("GEMINI_API_KEY가 없습니다.");const model=process.env.GEMINI_IMAGE_MODEL?.trim()||"gemini-3.1-flash-image",out=[];for(let i=0;i<n;i++){const endpoint=`https://generativelanguage.googleapis.com/v1/models/${encodeURIComponent(model)}:generateContent`;const r=await fetch(endpoint,{method:"POST",headers:{"x-goog-api-key":process.env.GEMINI_API_KEY,"Content-Type":"application/json"},body:JSON.stringify({contents:[{parts:[{text:prompt}]}],generationConfig:{responseModalities:["Image"],imageConfig:{aspectRatio:"4:5",imageSize:"1K"}}})});const raw=await r.text();let d;try{d=JSON.parse(raw)}catch{throw new Error("Gemini 응답을 읽지 못했습니다.")};if(!r.ok)throw new Error(d?.error?.message||`Gemini 오류 HTTP ${r.status}`);const found=extractGeminiImages(d);if(!found.length)throw new Error("Gemini 응답에 이미지가 없습니다.");found.forEach((u,j)=>out.push(imageResult("gemini",u,`${i}-${j}`)))}return out}
export default async function handler(req,res){res.setHeader("Cache-Control","no-store, max-age=0");if(req.method!=="POST")return res.status(405).json({error:"POST 요청만 지원합니다."});const{prompt,concept="hook",providers={},imageComposition={},role="insight",photoRequirement="required",templateType="photo-hook",designMode="photo-heavy",contentProfile={}}=req.body||{};if(!canGenerateImage({photoRequirement,templateType,designMode}))return res.status(400).json({error:"이 장표는 사진 생성 대상이 아닙니다."});const source=clean(prompt);if(!source)return res.status(400).json({error:"이미지 프롬프트가 없습니다."});const normalized={fal:count(providers.fal),replicate:count(providers.replicate),gemini:count(providers.gemini)};if(normalized.fal+normalized.replicate+normalized.gemini<1)return res.status(400).json({error:"이미지를 1장 이상 선택하세요."});const finalPrompt=buildPrompt(source,concept,imageComposition,role,designMode,contentProfile),images=[],providerErrors=[],jobs=[];if(normalized.fal)jobs.push(generateFal(finalPrompt,normalized.fal).then(x=>images.push(...x)).catch(e=>providerErrors.push({provider:"fal",message:e.message})));if(normalized.replicate)jobs.push(generateReplicate(finalPrompt,normalized.replicate).then(x=>images.push(...x)).catch(e=>providerErrors.push({provider:"replicate",message:e.message})));if(normalized.gemini)jobs.push(generateGemini(finalPrompt,normalized.gemini).then(x=>images.push(...x)).catch(e=>providerErrors.push({provider:"gemini",message:e.message})));await Promise.all(jobs);if(!images.length)return res.status(500).json({error:"생성된 이미지가 없습니다.",providerErrors});return res.status(200).json({success:true,images,providerErrors,finalPrompt})}
